- hosts: master, slave
  remote_user: root
  become: yes
  become_user: root
  become_method: sudo
  gather_facts: True
  roles:
    - common

- hosts: master
  remote_user: root
  become: yes
  become_user: root
  become_method: sudo
  gather_facts: True
  roles:
    - master-01
    - master-02
    - master-03

  vars:
    dir: /data/redis

- hosts: slave
  remote_user: root
  gather_facts: True
  roles:
    - slave-01
    - slave-02
    - slave-03
    
  vars:
    dir: /data/redis
    master_01_ip: "xxxxxxxxxx" 
    master_02_ip: "xxxxxxxxxx"
    master_03_ip: "xxxxxxxxxx"
    
- hosts: sentinel
  remote_user: root
  gather_facts: True
  roles:
    - sentinel-01
    - sentinel-02
    - sentinel-03

  vars:
    dir: /data/sentinel
    master_01_ip: "xxxxxxxxxxx" 
    master_02_ip: "xxxxxxxxxxx"
    master_03_ip: "xxxxxxxxxxx"
